### PR TITLE
Utilizing the new hydrate feature in BloomAlpha 3.8.0175

### PR DESCRIPTION
**Pull request by Aelazr**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/photostorytobloomconverter/9)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[PhotoStoryToBloomConverter/PhotoStoryToBloomConverter.csproj, line 16 [r1]](https://reviewable.io:443/reviews/bloombooks/photostorytobloomconverter/9#-KMAoBRHRzKjE_vh6fEi:-KMAoBRI2E1AuT3aBOyl:981126644) ([raw file](https://github.com/bloombooks/photostorytobloomconverter/blob/712436e19de653900a338e9e4d6fb023364830c5/PhotoStoryToBloomConverter/PhotoStoryToBloomConverter.csproj#L16)):_

> ``` XML
>     <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
>     <TargetFrameworkProfile />
>     <PublishUrl>publish\</PublishUrl>
> ```

I know this is a generated file, but do know why all these additions were made?

---

_[PhotoStoryToBloomConverter/Program.cs, line 166 [r1]](https://reviewable.io:443/reviews/bloombooks/photostorytobloomconverter/9#-KMAo6_YjmQKub74FY2V:-KMAo6_ZwZsVo3_ZS8QP:6290108) ([raw file](https://github.com/bloombooks/photostorytobloomconverter/blob/1667742208add1cb7d27c3e7399e71b1383262c5/PhotoStoryToBloomConverter/Program.cs#L166)):_

> ``` Smalltalk
>             //  the actual book, a generated html file built from the photostory project
>           CopyAssetsAndResources(Path.GetDirectoryName(projectXmlPath), convertedProjectDirectory);
>           CopyBloomFiles(convertedProjectDirectory);
> ```

Any reason to keep this method around?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/photostorytobloomconverter/9)_

**Comment by Aelazr** [comment]
Argh, no idea why that file changed those parts. I'll go ahead and remove those changes.

You are right, I'll remove the method.

**Comment by andrew-polk** [comment]
:lgtm:

---

Review status: 10 of 12 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/photostorytobloomconverter/9#-:-KMArP7aK9FmHWWQB1qH:1417088721)_

**Comment by andrew-polk** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/photostorytobloomconverter/9)_

**Pull request merged**
